// discoverAutomationCandidates.js — Local discovery without Claude
const { scoreAutomationOpportunity, rankOpportunities } = require('../scoring/automationScore');
const { calcAutomationROI, buildBusinessCase } = require('../roi/calculateAutomationROI');

// Catálogo de oportunidades conhecidas para SmartOps
const KNOWN_OPPORTUNITIES = [
  {
    id: 'SALES_LEAD_FOLLOWUP_WA',
    name: 'Follow-up de leads no WhatsApp',
    area: 'vendas',
    owner: 'Breno',
    frequency: 'diaria',
    time_per_execution: 0.5,
    monthly_volume: 60,
    current_tools: ['whatsapp_manual', 'planilha'],
    pain: 'Leads esfriam por falta de follow-up rápido',
    error_rate_pct: 30,
    error_cost_brl: 500,
    ai_needed: true,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: true,
    integrations: ['whatsapp', 'crm', 'n8n'],
    complexity: 'media',
    risk: 'baixo',
    monthly_cost_brl: 4500,
    error_rate_score: 7, process_clarity_score: 8, tech_ease_score: 7,
    impacto_financeiro_score: 8, reuse_score: 9, risk_score: 8,
    impl_hours: 12, impl_rate: 120, tool_cost: 80,
  },
  {
    id: 'MARKETING_INSTAGRAM_POST',
    name: 'Instagram Auto Post',
    area: 'marketing',
    owner: 'Breno',
    frequency: '3x_semana',
    time_per_execution: 1.5,
    monthly_volume: 12,
    current_tools: ['instagram_manual', 'canva'],
    pain: 'Publicação inconsistente, gasta muito tempo',
    error_rate_pct: 10,
    error_cost_brl: 100,
    ai_needed: true,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['instagram', 'n8n', 'supabase'],
    complexity: 'baixa',
    risk: 'baixo',
    monthly_cost_brl: 1800,
    error_rate_score: 5, process_clarity_score: 9, tech_ease_score: 8,
    impacto_financeiro_score: 6, reuse_score: 8, risk_score: 9,
    impl_hours: 8, impl_rate: 120, tool_cost: 50,
  },
  {
    id: 'SALES_PROPOSAL_GEN',
    name: 'Geração automática de proposta',
    area: 'vendas',
    owner: 'Breno',
    frequency: 'semanal',
    time_per_execution: 3,
    monthly_volume: 4,
    current_tools: ['word', 'email'],
    pain: 'Proposta demora 3h para criar, cliente espera muito',
    error_rate_pct: 15,
    error_cost_brl: 800,
    ai_needed: true,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['anthropic', 'n8n', 'gmail', 'crm'],
    complexity: 'media',
    risk: 'medio',
    monthly_cost_brl: 1600,
    error_rate_score: 6, process_clarity_score: 7, tech_ease_score: 9,
    impacto_financeiro_score: 7, reuse_score: 7, risk_score: 6,
    impl_hours: 10, impl_rate: 120, tool_cost: 60,
  },
  {
    id: 'OPS_WEEKLY_REPORT',
    name: 'Relatório semanal de cliente',
    area: 'operacoes',
    owner: 'Breno',
    frequency: 'semanal',
    time_per_execution: 2,
    monthly_volume: 4,
    current_tools: ['google_docs', 'planilha'],
    pain: '2h toda semana montando relatório que poderia ser automático',
    error_rate_pct: 5,
    error_cost_brl: 200,
    ai_needed: true,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['anthropic', 'n8n', 'supabase', 'google_sheets'],
    complexity: 'baixa',
    risk: 'baixo',
    monthly_cost_brl: 1200,
    error_rate_score: 4, process_clarity_score: 9, tech_ease_score: 9,
    impacto_financeiro_score: 5, reuse_score: 8, risk_score: 9,
    impl_hours: 6, impl_rate: 120, tool_cost: 30,
  },
  {
    id: 'CLIENT_ONBOARDING',
    name: 'Onboarding automático de novo cliente',
    area: 'operacoes',
    owner: 'Breno',
    frequency: 'mensal',
    time_per_execution: 3,
    monthly_volume: 2,
    current_tools: ['email', 'whatsapp', 'google_drive'],
    pain: 'Onboarding inconsistente, esquece de enviar materiais',
    error_rate_pct: 20,
    error_cost_brl: 300,
    ai_needed: false,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['n8n', 'gmail', 'google_drive', 'whatsapp'],
    complexity: 'baixa',
    risk: 'baixo',
    monthly_cost_brl: 600,
    error_rate_score: 6, process_clarity_score: 8, tech_ease_score: 8,
    impacto_financeiro_score: 4, reuse_score: 7, risk_score: 9,
    impl_hours: 5, impl_rate: 120, tool_cost: 20,
  },
  {
    id: 'ADS_DAILY_ALERT',
    name: 'Alerta diário de performance Ads',
    area: 'marketing',
    owner: 'Breno',
    frequency: 'diaria',
    time_per_execution: 0.25,
    monthly_volume: 30,
    current_tools: ['google_ads_manual', 'meta_ads_manual'],
    pain: 'Anomalias em Ads não detectadas rápido custam dinheiro',
    error_rate_pct: 40,
    error_cost_brl: 200,
    ai_needed: false,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['google_ads', 'meta_ads', 'n8n', 'telegram'],
    complexity: 'baixa',
    risk: 'baixo',
    monthly_cost_brl: 750,
    error_rate_score: 8, process_clarity_score: 9, tech_ease_score: 8,
    impacto_financeiro_score: 5, reuse_score: 8, risk_score: 9,
    impl_hours: 4, impl_rate: 120, tool_cost: 20,
  },
  {
    id: 'FINANCE_INVOICE_REMINDER',
    name: 'Cobrança automática e follow-up de pagamento',
    area: 'financeiro',
    owner: 'Breno',
    frequency: 'mensal',
    time_per_execution: 1,
    monthly_volume: 3,
    current_tools: ['whatsapp_manual', 'email_manual'],
    pain: 'Cobranças esquecidas, inadimplência desnecessária',
    error_rate_pct: 25,
    error_cost_brl: 1000,
    ai_needed: false,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: false,
    integrations: ['n8n', 'whatsapp', 'gmail'],
    complexity: 'baixa',
    risk: 'baixo',
    monthly_cost_brl: 800,
    error_rate_score: 7, process_clarity_score: 9, tech_ease_score: 8,
    impacto_financeiro_score: 5, reuse_score: 8, risk_score: 9,
    impl_hours: 4, impl_rate: 120, tool_cost: 20,
  },
  {
    id: 'SALES_WHATSAPP_LEAD_QUALIFY',
    name: 'Bot WhatsApp qualificação de leads',
    area: 'vendas',
    owner: 'Breno',
    frequency: 'diaria',
    time_per_execution: 1,
    monthly_volume: 30,
    current_tools: ['whatsapp_manual'],
    pain: 'Qualificar leads manualmente consome horas e tem inconsistência',
    error_rate_pct: 35,
    error_cost_brl: 400,
    ai_needed: true,
    n8n_workflow_needed: true,
    whatsapp_bot_needed: true,
    integrations: ['whatsapp', 'n8n', 'crm', 'anthropic'],
    complexity: 'media',
    risk: 'baixo',
    monthly_cost_brl: 4500,
    error_rate_score: 8, process_clarity_score: 7, tech_ease_score: 7,
    impacto_financeiro_score: 9, reuse_score: 10, risk_score: 7,
    impl_hours: 16, impl_rate: 120, tool_cost: 100,
  },
];

function discoverCandidatesLocally(area = null) {
  let candidates = KNOWN_OPPORTUNITIES;
  if (area) candidates = candidates.filter(c => c.area === area);

  const scored = rankOpportunities(candidates).map(c => {
    const roi = calcAutomationROI({
      hours_per_execution:    c.time_per_execution,
      monthly_volume:         c.monthly_volume,
      error_rate_pct:         c.error_rate_pct,
      error_cost_brl:         c.error_cost_brl,
      implementation_hours:   c.impl_hours,
      implementation_rate:    c.impl_rate,
      tool_cost_monthly_brl:  c.tool_cost,
    });
    return { ...c, roi, business_case: buildBusinessCase(c.name, roi, c) };
  });

  const top5 = scored.slice(0, 5);
  const portfolio = scored.reduce((acc, c) => {
    acc.total_hours_saved += c.roi.hours_saved_month;
    acc.total_monthly_savings += c.roi.net_monthly_savings;
    return acc;
  }, { total_hours_saved: 0, total_monthly_savings: 0 });

  return {
    total_candidates: scored.length,
    area_filter:      area || 'todas',
    candidates:       scored,
    top_5:            top5,
    portfolio_summary: {
      total_hours_saved_month:  Math.round(portfolio.total_hours_saved * 10) / 10,
      total_monthly_savings:    Math.round(portfolio.total_monthly_savings),
      total_annual_savings:     Math.round(portfolio.total_monthly_savings * 12),
    },
    discovery_date: new Date().toISOString().split('T')[0],
  };
}

module.exports = { discoverCandidatesLocally, KNOWN_OPPORTUNITIES };
