// Productization Intelligence Agent — config
const CONFIG = {
  agent: {
    name:    'Productization Intelligence Agent',
    version: '1.0.0',
    role:    'Diretor de Produtos, Ofertas e Escalabilidade',
    mission: 'Transformar conhecimento e serviços da SmartOps IA em produtos replicáveis e escaláveis',
  },

  company: {
    name:     'SmartOps IA',
    owner:    'Breno Luiz',
    location: 'Belo Horizonte, MG',
    services: ['Lean Six Sigma', 'Melhoria Contínua', 'Automação', 'IA para PMEs'],
    target:   'PMEs em BH e região metropolitana',
  },

  // Escada de valor SmartOps
  price_ladder: {
    free:      { label: 'Gratuito',           range: [0, 0],           funnel_role: 'lead_magnet' },
    entry:     { label: 'Entrada',             range: [47, 297],        funnel_role: 'tripwire' },
    b2b_low:   { label: 'B2B Baixo Ticket',   range: [497, 1500],      funnel_role: 'qualifier' },
    core:      { label: 'Core',               range: [3500, 15000],    funnel_role: 'main_revenue' },
    premium:   { label: 'Premium',            range: [15000, 100000],  funnel_role: 'high_ticket' },
    recurring: { label: 'Recorrência',        range: [1500, 10000],    funnel_role: 'mrr' },
  },

  // Catálogo de produtos iniciais recomendados
  initial_products: {
    'checklist-desperdicios': {
      id:           'checklist-desperdicios',
      name:         'Checklist de Desperdícios Lean para PMEs',
      category:     'lead_magnet',
      price:        0,
      tier:         'free',
      funnel_role:  'lead_magnet',
      target:       'Donos de PMEs que não conhecem Lean',
      pain:         'Não sei se minha empresa tem desperdícios',
      promise:      'Descubra em 5 minutos onde sua empresa está perdendo dinheiro',
      deliverables: ['Checklist PDF', '35 pontos de verificação', 'Score de desperdício', 'Próximo passo'],
      format:       'PDF + formulário',
      cost_to_deliver: 0,
      margin:       100,
      scalability:  'ilimitada',
      upsell:       'diagnostico-express',
      status:       'idea',
      score:        92,
    },
    'diagnostico-express': {
      id:           'diagnostico-express',
      name:         'Diagnóstico Express SmartOps',
      category:     'diagnostic',
      price:        997,
      tier:         'b2b_low',
      funnel_role:  'qualifier',
      target:       'Donos de PMEs que querem saber onde melhorar a operação',
      pain:         'Sei que tem problema, mas não sei onde está',
      promise:      'Em 3 dias você sabe exatamente onde sua operação está perdendo dinheiro e o que fazer',
      deliverables: ['Formulário inicial', 'Reunião 60 min', 'Mapa de gargalos', 'Relatório PDF', 'Plano de ação', 'Estimativa de ROI', 'Proposta de continuidade'],
      format:       'Presencial ou online — BH e região',
      cost_to_deliver: 200,
      margin:        80,
      scalability:  'média — exige tempo do consultor',
      upsell:       'lean-ai-sprint',
      status:       'idea',
      score:        91,
    },
    'mapa-gargalos': {
      id:           'mapa-gargalos',
      name:         'Mapa de Gargalos Operacionais',
      category:     'consulting_product',
      price:        2500,
      tier:         'b2b_low',
      funnel_role:  'qualifier',
      target:       'PMEs com processo travado ou crescimento desorganizado',
      pain:         'Minha empresa cresceu mas a operação virou caos',
      promise:      'Mapeie todos os gargalos da sua operação e tenha um plano de prioridade para os próximos 90 dias',
      deliverables: ['Mapeamento de processos (VSM)', 'Identificação de top 5 gargalos', 'Análise de causa raiz', 'Plano priorizado de melhoria', 'Apresentação executiva'],
      format:       'Presencial BH — 1 a 2 dias',
      cost_to_deliver: 500,
      margin:        80,
      scalability:  'baixa — presencial',
      upsell:       'lean-ai-sprint',
      status:       'idea',
      score:        88,
    },
    'sprint-automacao': {
      id:           'sprint-automacao',
      name:         'Sprint de Automação n8n',
      category:     'implementation',
      price:        6500,
      tier:         'core',
      funnel_role:  'main_revenue',
      target:       'PMEs com tarefas manuais repetitivas que consomem tempo da equipe',
      pain:         'Minha equipe passa horas fazendo tarefas que poderiam ser automáticas',
      promise:      'Em 2 semanas você tem 1 a 3 automações críticas funcionando e sua equipe de volta ao que importa',
      deliverables: ['Mapeamento das tarefas a automatizar', 'Desenvolvimento e implantação das automações', 'Treinamento da equipe', 'Documentação', 'Suporte 30 dias'],
      format:       'Online ou presencial BH',
      cost_to_deliver: 1200,
      margin:        82,
      scalability:  'média',
      upsell:       'smartops-monthly',
      status:       'idea',
      score:        87,
    },
    'lean-ai-sprint': {
      id:           'lean-ai-sprint',
      name:         'Lean AI Sprint',
      category:     'implementation',
      price:        10000,
      tier:         'core',
      funnel_role:  'main_revenue',
      target:       'PMEs que querem transformar operação com Lean + IA em 30 dias',
      pain:         'Preciso organizar processos, reduzir custos e automatizar, mas não sei por onde começar',
      promise:      'Em 30 dias sua operação tem processos mapeados, principais desperdiços eliminados, indicadores no ar e automações críticas funcionando',
      deliverables: ['Diagnóstico completo', 'Mapeamento e otimização de processos', 'Eliminação dos top 3 desperdícios', 'Dashboard de indicadores', 'Sprint de automação', 'Plano de melhoria contínua'],
      format:       'Presencial BH + reuniões semanais',
      cost_to_deliver: 2000,
      margin:        80,
      scalability:  'baixa',
      upsell:       'smartops-monthly',
      status:       'idea',
      score:        90,
    },
    'smartops-monthly': {
      id:           'smartops-monthly',
      name:         'SmartOps Monthly — Melhoria Contínua Mensal',
      category:     'subscription',
      price:        3500,
      tier:         'recurring',
      funnel_role:  'mrr',
      target:       'Clientes que já passaram pelo diagnóstico ou sprint e querem manutenção',
      pain:         'Preciso manter a melhoria contínua mas não tenho como fazer sozinho todo mês',
      promise:      'Toda semana sua operação melhora um pouco mais — com acompanhamento, indicadores, automações e decisões orientadas por dados',
      deliverables: ['Reunião semanal 30 min', 'Dashboard atualizado', 'Análise de indicadores', 'Uma melhoria ou automação por mês', 'Acesso a templates SmartOps', 'Relatório mensal'],
      format:       'Online — reuniões + async',
      cost_to_deliver: 700,
      margin:        80,
      scalability:  'média — até 5 clientes simultâneos por consultor',
      upsell:       'lean-ai-sprint',
      status:       'idea',
      score:        93,
    },
  },

  // Pesos do productization score (total 100)
  scoring_weights: {
    demanda:            20,
    dor_forte:          15,
    facilidade_entrega: 15,
    escalabilidade:     15,
    margem:             15,
    fit_smartops:       10,
    potencial_upsell:   10,
  },

  // Classificação do score
  score_classification: {
    LAUNCH_NOW:  { min: 85, label: 'Criar e vender imediatamente', action: 'Criar MVP e lançar' },
    VALIDATE:    { min: 70, label: 'Validar com teste rápido',     action: 'Criar landing page de teste' },
    BACKLOG:     { min: 50, label: 'Guardar no backlog',           action: 'Monitorar demanda' },
    DISCARD:     { min: 0,  label: 'Não priorizar',                action: 'Arquivar ideia' },
  },

  // Status de produto
  product_statuses: [
    'idea', 'scored', 'backlog', 'validation_planned', 'validating',
    'validated', 'rejected', 'mvp_building', 'ready_to_launch',
    'launched', 'selling', 'optimizing', 'scaled', 'archived',
  ],

  claude: { model: 'claude-sonnet-4-6', maxTokens: 4096 },
};

module.exports = { CONFIG };
