/**
 * daily_tasks_config.js — SmartOps IA
 * Master config de todos os agentes: modo diário, tarefas, squad, prioridade.
 * Usado por: daily_master_runner.js, validate_all_agents.js
 */

const AGENTS = [
  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD MARKETING
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'marketing-research',
    folder: 'marketing-research-agent',
    entry: 'marketing_research_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Pesquisar tendências do dia em Lean, Six Sigma, Automação e IA para PMEs',
      'Identificar tópicos de alta busca no nicho de consultoria operacional BH/MG',
      'Mapear movimentos dos concorrentes nas últimas 24h',
      'Gerar 3 ideias de conteúdo com alto potencial de engajamento',
      'Briefing de oportunidades de mercado para o dia',
    ],
    telegram_title: '🔍 PESQUISA DE MERCADO',
    output_file: 'research_report.md',
  },
  {
    key: 'copywriter',
    folder: 'copywriter-agent',
    entry: 'copywriter_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Gerar hooks para Instagram baseados nas tendências do dia',
      'Criar 3 variações de CTA para os serviços SmartOps',
      'Produzir legenda pronta para o próximo post',
      'Avaliar performance do último copy publicado',
      'Sugerir tema e ângulo para o próximo reels',
    ],
    telegram_title: '✍️ COPYWRITER',
    output_file: 'copy_report.md',
  },
  {
    key: 'seo',
    folder: 'seo-agent',
    entry: 'seo_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Analisar posicionamento das keywords estratégicas no Google',
      'Identificar oportunidades de conteúdo orgânico com baixa concorrência',
      'Verificar Search Console: cliques, impressões, CTR',
      'Sugerir 3 otimizações de SEO on-page prioritárias',
      'Mapear clusters de conteúdo a produzir esta semana',
    ],
    telegram_title: '🔎 SEO',
    output_file: 'seo_report.md',
  },
  {
    key: 'content-performance',
    folder: 'content-performance-agent',
    entry: 'content_performance_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Analisar engajamento dos últimos 7 posts (likes, saves, compartilhamentos)',
      'Identificar o conteúdo de melhor performance da semana',
      'Calcular CTR de cada formato (reels vs carrossel vs foto)',
      'Alertar sobre conteúdo com performance abaixo da meta',
      'Recomendar formato e tema para próxima publicação',
    ],
    telegram_title: '📊 PERFORMANCE DE CONTEÚDO',
    output_file: 'content_performance_report.md',
  },
  {
    key: 'personal-brand',
    folder: 'personal-brand-agent',
    entry: 'personal_brand_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Avaliar consistência da marca pessoal nos últimos posts',
      'Verificar crescimento de seguidores vs meta',
      'Identificar oportunidades de posicionamento como autoridade',
      'Sugerir 1 ação de networking ou colaboração para o dia',
      'Score de maturidade da marca pessoal (0-100)',
    ],
    telegram_title: '👤 MARCA PESSOAL',
    output_file: 'personal_brand_report.md',
  },
  {
    key: 'distribution',
    folder: 'distribution-agent',
    entry: 'distribution_agent.js',
    squad: 'marketing',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Verificar status das publicações programadas do dia',
      'Confirmar calendário editorial desta semana',
      'Checar se há conteúdo aprovado aguardando publicação',
      'Monitorar performance das últimas publicações em todos os canais',
      'Alertar sobre gaps no calendário',
    ],
    telegram_title: '📅 DISTRIBUIÇÃO',
    output_file: 'distribution_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD GROWTH
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'ads',
    folder: 'ads-agent',
    entry: 'ads_agent.js',
    squad: 'growth',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Analisar ROAS, CPA e CTR de todas as campanhas ativas',
      'Identificar campanhas com CPA acima do limite (alerta P1)',
      'Verificar criativos com fadiga (frequência > 3.5)',
      'Calcular budget restante e projeção até fim do mês',
      'Recomendar 1 ação de otimização de alto impacto',
    ],
    telegram_title: '💰 ADS (GOOGLE + META)',
    output_file: 'ads_report.md',
  },
  {
    key: 'cro',
    folder: 'cro-agent',
    entry: 'cro_agent.js',
    squad: 'growth',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Calcular taxa de conversão atual vs meta (diagnóstico gratuito)',
      'Analisar abandono no funil: visita → lead → reunião → proposta',
      'Identificar maior gargalo de conversão hoje',
      'Verificar performance da landing page /diagnostico-gratuito',
      'Sugerir 1 teste A/B de alto impacto',
    ],
    telegram_title: '🎯 CONVERSÃO (CRO)',
    output_file: 'cro_report.md',
  },
  {
    key: 'website-analytics',
    folder: 'website-analytics-agent',
    entry: 'website_analytics_agent.js',
    squad: 'growth',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Sessões, usuários únicos e taxa de rejeição das últimas 24h',
      'Top 5 páginas por tráfego e conversão',
      'Origem do tráfego: orgânico vs pago vs social vs direto',
      'Eventos GA4 críticos disparados (formulário, WhatsApp, CTA)',
      'Alertar se sessões caírem mais de 20% vs média',
    ],
    telegram_title: '🌐 ANALYTICS DO SITE',
    output_file: 'analytics_report.md',
  },
  {
    key: 'lead-scoring',
    folder: 'lead-scoring-agent',
    entry: 'lead_scoring_agent.js',
    squad: 'growth',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Score BANT de todos os leads do CRM (A/B/C/D)',
      'Identificar leads A/B aguardando follow-up há mais de 48h',
      'Listar top 3 leads prioritários para contato hoje',
      'Calcular taxa de qualificação da semana',
      'Alertar sobre leads quentes que podem esfriar',
    ],
    telegram_title: '🏆 LEAD SCORING',
    output_file: 'lead_scoring_report.md',
  },
  {
    key: 'revenue',
    folder: 'revenue-agent',
    entry: 'revenue_agent.js',
    squad: 'growth',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'MRR atual vs meta do mês (R$)',
      'CAC por canal e LTV/CAC ratio',
      'Pipeline de vendas: valor total e probabilidade de fechamento',
      'Projeção de receita para os próximos 30 dias',
      'Alertar se MRR estiver mais de 20% abaixo da meta',
    ],
    telegram_title: '💵 RECEITA',
    output_file: 'revenue_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD OPERATIONS
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'lean',
    folder: 'lean-agent',
    entry: 'lean_agent.js',
    squad: 'operations',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Escanear 8 desperdícios TIMWOODS nos processos da SmartOps',
      'Calcular lead time dos processos comercial, entrega e marketing',
      'Identificar gargalos no fluxo de valor atual',
      'Sugerir 1 Quick Win Lean implementável hoje',
      'Score de maturidade Lean da operação (0-100)',
    ],
    telegram_title: '⚙️ LEAN',
    output_file: 'lean_report.md',
  },
  {
    key: 'process-mining',
    folder: 'process-mining-agent',
    entry: 'process_mining_agent.js',
    squad: 'operations',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Analisar logs dos processos: pipeline, agentes, n8n',
      'Detectar desvios de conformidade nos workflows',
      'Mapear bottlenecks com maior tempo de espera',
      'Identificar processos que ultrapassaram SLA definido',
      'Recomendar melhoria de processo de maior impacto',
    ],
    telegram_title: '🔬 PROCESS MINING',
    output_file: 'process_mining_report.md',
  },
  {
    key: 'kaizen',
    folder: 'kaizen-agent',
    entry: 'kaizen_agent.js',
    squad: 'operations',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Checar status das melhorias em andamento (ciclo PDCA)',
      'Calcular ROI das melhorias implementadas esta semana',
      'Identificar 1 oportunidade de melhoria contínua para hoje',
      'Registrar lição aprendida do dia anterior',
      'Atualizar score de maturidade de melhoria contínua',
    ],
    telegram_title: '🔄 KAIZEN',
    output_file: 'kaizen_report.md',
  },
  {
    key: 'automation',
    folder: 'automation-agent',
    entry: 'automation_agent.js',
    squad: 'operations',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Status de todas as automações ativas (n8n, rotinas)',
      'Identificar automações com falha ou timeout nas últimas 24h',
      'Calcular horas economizadas por automação esta semana',
      'Listar processos manuais prioritários para automatizar',
      'Alertar P1 se automação crítica falhou',
    ],
    telegram_title: '🤖 AUTOMAÇÃO',
    output_file: 'automation_report.md',
  },
  {
    key: 'six-sigma',
    folder: 'six-sigma-agent',
    entry: 'six_sigma_agent.js',
    squad: 'operations',
    priority: 'daily',
    daily_mode: 'brief',
    daily_tasks: [
      'DPMO e nível sigma dos processos principais',
      'Identificar processo com maior variabilidade hoje',
      'Status dos projetos DMAIC em andamento',
      'Calcular Cp/Cpk se dados de processo disponíveis',
      'Recomendação de ação corretiva de maior impacto',
    ],
    telegram_title: '📐 SIX SIGMA',
    output_file: 'six_sigma_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD SALES
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'sales-intelligence',
    folder: 'sales-intelligence-agent',
    entry: 'sales_agent.js',
    squad: 'sales',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Analisar pipeline: leads → reuniões → propostas → fechamentos',
      'Taxa de conversão por etapa vs meta semanal',
      'Objeções mais frequentes dos últimos 7 dias e como tratar',
      'Top 3 ações comerciais prioritárias para hoje',
      'Identificar cliente em risco de não fechar (follow-up urgente)',
    ],
    telegram_title: '🎯 VENDAS',
    output_file: 'sales_report.md',
  },
  {
    key: 'offer-optimization',
    folder: 'offer-optimization-agent',
    entry: 'offer_optimization_agent.js',
    squad: 'sales',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Score de cada oferta SmartOps (diagnóstico gratuito, sprints, mensalidade)',
      'Identificar oferta com menor taxa de conversão',
      'Sugerir otimização de copy ou estrutura de oferta',
      'Verificar se preços estão alinhados com mercado',
      'Recomendar bundle ou upgrade para clientes atuais',
    ],
    telegram_title: '📦 OFERTAS',
    output_file: 'offer_report.md',
  },
  {
    key: 'proposal',
    folder: 'proposal-agent',
    entry: 'proposal_agent.js',
    squad: 'sales',
    priority: 'daily',
    daily_mode: 'roi',
    daily_tasks: [
      'Status de todas as propostas abertas (aguardando resposta)',
      'Calcular ROI esperado para o cliente de cada proposta',
      'Identificar proposta com follow-up vencido',
      'Sugerir ajuste de proposta para aumentar aceitação',
      'Score de qualidade de cada proposta enviada',
    ],
    telegram_title: '📄 PROPOSTAS',
    output_file: 'proposals_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD EXECUTIVE
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'competitor-intelligence',
    folder: 'competitor-intelligence-agent',
    entry: 'competitor_agent.js',
    squad: 'executive',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Monitorar postagens e movimentos dos top 7 concorrentes',
      'Identificar novo conteúdo ou oferta de concorrente (alerta)',
      'Calcular share of voice nas keywords estratégicas',
      'Verificar menções à SmartOps IA nas redes sociais',
      'Oportunidade de diferenciação identificada no dia',
    ],
    telegram_title: '🕵️ INTELIGÊNCIA COMPETITIVA',
    output_file: 'competitor_report.md',
  },
  {
    key: 'strategic-planning',
    folder: 'strategic-planning-agent',
    entry: 'strategic_planning.js',
    squad: 'executive',
    priority: 'daily',
    daily_mode: 'brief',
    daily_tasks: [
      'Progresso vs OKRs da semana (% de conclusão)',
      'Verificar se há desvio estratégico (drift detection)',
      'Status das iniciativas prioritárias do plano 90 dias',
      'Identificar risco estratégico de maior impacto hoje',
      'Próxima milestone crítica e prazo',
    ],
    telegram_title: '🗺️ ESTRATÉGIA',
    output_file: 'strategy_report.md',
  },
  {
    key: 'executive-dashboard',
    folder: 'executive-dashboard-agent',
    entry: 'executive_dashboard_agent.js',
    squad: 'executive',
    priority: 'daily',
    daily_mode: 'daily',
    daily_tasks: [
      'Dashboard executivo: score geral do negócio (0-100)',
      'KPIs críticos em alerta vs no verde',
      'Top 3 ações prioritárias do dia baseadas em dados',
      'Comparativo dia de hoje vs semana passada',
      'Alertas P1 que requerem atenção imediata',
    ],
    telegram_title: '📋 DASHBOARD EXECUTIVO',
    output_file: 'executive_dashboard.md',
  },
  {
    key: 'chief-of-staff',
    folder: 'chief-of-staff-agent',
    entry: 'chief_of_staff_agent.js',
    squad: 'executive',
    priority: 'daily',
    daily_mode: 'standup',
    daily_tasks: [
      'Plano de execução do dia: tarefas por prioridade (P1/P2/P3)',
      'Status das entregas da semana: concluído vs pendente',
      'Delegar ou redesenhar tarefas sem responsável definido',
      'Verificar OKRs: progresso vs meta desta semana',
      'Preparar agenda do dia com foco no que move a agulha',
    ],
    telegram_title: '📌 CHIEF OF STAFF',
    output_file: 'chief_of_staff_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD FINANCE
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'financial-intelligence',
    folder: 'financial-intelligence-agent',
    entry: 'financial_agent.js',
    squad: 'finance',
    priority: 'daily',
    daily_mode: 'dashboard',
    daily_tasks: [
      'Receita acumulada do mês vs meta (R$15k)',
      'Margem de contribuição por serviço',
      'Fluxo de caixa: entradas e saídas das últimas 24h',
      'Projeção de receita até fim do mês',
      'Alerta se runway cair abaixo de 60 dias',
    ],
    telegram_title: '💰 FINANCEIRO',
    output_file: 'financial_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // SQUAD CLIENT SUCCESS
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'client-success',
    folder: 'client-success-agent',
    entry: 'client_success_agent.js',
    squad: 'client',
    priority: 'daily',
    daily_mode: 'report',
    daily_tasks: [
      'Health score de todos os clientes ativos (0-100)',
      'Identificar cliente em risco de churn (score < 60)',
      'Verificar entregas pendentes com prazo próximo',
      'Status do onboarding de novos clientes',
      'Ação de retenção prioritária para hoje',
    ],
    telegram_title: '🤝 CLIENT SUCCESS',
    output_file: 'client_success_report.md',
  },
  {
    key: 'risk',
    folder: 'risk-agent',
    entry: 'risk_agent.js',
    squad: 'client',
    priority: 'daily',
    daily_mode: 'scan',
    daily_tasks: [
      'Scan automático de riscos: pipeline, financeiro, operacional, clientes',
      'Alertas P1: riscos que requerem ação imediata',
      'Verificar indicadores de risco de cada cliente',
      'Risco financeiro: runway, concentração de receita, inadimplência',
      'Plano de contingência para risco de maior probabilidade',
    ],
    telegram_title: '⚠️ RISCOS',
    output_file: 'risk_report.md',
  },

  // ──────────────────────────────────────────────────────────────────────────
  // CEO ADVISOR — consolida tudo (roda por último)
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'ceo-advisor',
    folder: 'ceo-advisor-agent',
    entry: 'ceo_advisor_agent.js',
    squad: 'executive',
    priority: 'daily',
    daily_mode: 'brief',
    daily_tasks: [
      'Consolidar insights de todos os squads do dia',
      'Priorizar as 3 ações de maior ROI para hoje',
      'Decisão executiva recomendada (P1 urgente)',
      'Score de saúde geral do negócio (0-100)',
      'Alerta P1 se há algo que precisa de ação imediata do Breno',
    ],
    telegram_title: '🧠 CEO ADVISOR (CONSOLIDADO)',
    output_file: 'ceo_brief.md',
    runs_last: true, // sempre roda por último
  },

  // ──────────────────────────────────────────────────────────────────────────
  // AGENTES SEMANAIS (rodam toda segunda-feira)
  // ──────────────────────────────────────────────────────────────────────────
  {
    key: 'partnership',
    folder: 'partnership-agent',
    entry: 'partnership_agent.js',
    squad: 'brand',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Top parceiros estratégicos a abordar esta semana',
      'Status de parcerias em negociação',
      'Comissão acumulada por parceiro',
      'Nova oportunidade de co-marketing identificada',
      'Follow-up de parceria pendente',
    ],
    telegram_title: '🤝 PARCERIAS',
    output_file: 'partnership_report.md',
  },
  {
    key: 'authority-building',
    folder: 'authority-building-agent',
    entry: 'authority_agent.js',
    squad: 'brand',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Score de autoridade atual (0-100)',
      'Oportunidades de palestra, podcast ou artigo esta semana',
      'Status das iniciativas de autoridade em andamento',
      'Próxima ação de construção de autoridade (alto impacto)',
      'Métricas de reach e engagement de conteúdo de autoridade',
    ],
    telegram_title: '🏆 AUTORIDADE',
    output_file: 'authority_report.md',
  },
  {
    key: 'case-study',
    folder: 'case-study-agent',
    entry: 'case_study_agent.js',
    squad: 'knowledge',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Novos estudos de caso disponíveis para criar',
      'Status dos cases em produção',
      'ROI documentado dos últimos projetos entregues',
      'Case de maior impacto para priorizar esta semana',
      'Repurposing: case que pode virar post, vídeo ou proposta',
    ],
    telegram_title: '📑 CASES',
    output_file: 'case_study_report.md',
  },
  {
    key: 'knowledge-management',
    folder: 'knowledge-management-agent',
    entry: 'knowledge_management_agent.js',
    squad: 'knowledge',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Gaps de conhecimento identificados (SOPs faltando)',
      'Documentos que precisam de atualização',
      'Score de maturidade da base de conhecimento',
      'Lição aprendida mais importante da semana',
      'Próximo SOP ou playbook a criar',
    ],
    telegram_title: '📚 KNOWLEDGE',
    output_file: 'knowledge_report.md',
  },
  {
    key: 'productization',
    folder: 'productization-agent',
    entry: 'productization_agent.js',
    squad: 'knowledge',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Score de cada produto/serviço SmartOps (produtizável)',
      'Progresso do roadmap de produtização',
      'Produto de maior potencial para escalar esta semana',
      'Feedback de clientes que pode melhorar algum produto',
      'Oportunidade de novo produto recorrente identificada',
    ],
    telegram_title: '🏭 PRODUTIZAÇÃO',
    output_file: 'productization_report.md',
  },
  {
    key: 'organizational-learning',
    folder: 'organizational-learning-agent',
    entry: 'organizational_learning.js',
    squad: 'knowledge',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Retrospectiva semanal: o que funcionou / o que não funcionou',
      'Lições aprendidas mais valiosas da semana',
      'Padrões de erro recorrente (e como eliminar)',
      'Melhoria de processo mais impactante identificada',
      'Score de maturidade de aprendizado organizacional',
    ],
    telegram_title: '🎓 APRENDIZADO ORGANIZACIONAL',
    output_file: 'learning_report.md',
  },
  {
    key: 'market-opportunity',
    folder: 'market-opportunity-agent',
    entry: 'market_opportunity.js',
    squad: 'executive',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Top 3 oportunidades de mercado desta semana em BH/MG',
      'Nichos com maior demanda por consultoria Lean/IA',
      'Prospect de alto potencial identificado',
      'Tendência emergente no mercado de PMEs',
      'Oportunidade com maior ROI e menor concorrência',
    ],
    telegram_title: '🎯 OPORTUNIDADES DE MERCADO',
    output_file: 'market_opportunity_report.md',
  },
  {
    key: 'growth-intelligence',
    folder: 'growth-intelligence-agent',
    entry: 'growth_intelligence_agent.js',
    squad: 'growth',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'AARRR: Aquisição, Ativação, Retenção, Receita, Referral esta semana',
      'Canal com melhor CAC e maior potencial de escala',
      'Alavanca de crescimento de maior impacto identificada',
      'North Star Metric: progresso vs meta',
      'Experimento de crescimento a rodar esta semana',
    ],
    telegram_title: '🚀 GROWTH INTELLIGENCE',
    output_file: 'growth_report.md',
  },
  {
    key: 'revenue-intelligence',
    folder: 'revenue-intelligence-agent',
    entry: 'revenue_intelligence_agent.js',
    squad: 'growth',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Forecasting de receita: próximos 30/60/90 dias',
      'Padrões de receita: sazonalidade, churn, expansão',
      'Cohort de clientes: LTV por período de aquisição',
      'Risco de churn baseado em padrões comportamentais',
      'Ação para aumentar LTV dos clientes atuais',
    ],
    telegram_title: '📈 INTELIGÊNCIA DE RECEITA',
    output_file: 'revenue_intelligence_report.md',
  },
  {
    key: 'experimentation',
    folder: 'experimentation-agent',
    entry: 'experimentation_agent.js',
    squad: 'growth',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Status de experimentos A/B em andamento',
      'Resultado do último experimento concluído',
      'Próxima hipótese a testar (maior ICE score)',
      'Aprendizado de maior impacto dos experimentos desta semana',
      'Backlog priorizado de testes por canal',
    ],
    telegram_title: '🧪 EXPERIMENTAÇÃO',
    output_file: 'experimentation_report.md',
  },
  {
    key: 'customer-journey',
    folder: 'customer-journey-agent',
    entry: 'customer_journey_agent.js',
    squad: 'growth',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Health score da jornada completa do cliente (0-100)',
      'Principal ponto de fricção na jornada esta semana',
      'Touchpoint com menor satisfação identificado',
      'Oportunidade de melhoria na jornada de maior impacto',
      'Tempo médio de cada etapa: awareness → fechamento',
    ],
    telegram_title: '🗺️ JORNADA DO CLIENTE',
    output_file: 'customer_journey_report.md',
  },
  {
    key: 'ai-automation',
    folder: 'ai-automation-agent',
    entry: 'ai_automation_agent.js',
    squad: 'operations',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Automações com IA rodando: status e ROI acumulado',
      'Novo caso de uso de IA identificado para SmartOps',
      'Performance dos agentes Claude nas últimas 24h',
      'Sugestão de automação com IA de maior impacto',
      'Integração entre sistemas: gargalos e oportunidades',
    ],
    telegram_title: '🤖 AUTOMAÇÃO COM IA',
    output_file: 'ai_automation_report.md',
  },
  {
    key: 'lean-consulting',
    folder: 'lean-consulting-agent',
    entry: 'lean_consulting_agent.js',
    squad: 'operations',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Status dos projetos Lean em andamento com clientes',
      'Métricas de impacto: lead time, retrabalho, desperdício eliminado',
      'Próxima fase do diagnóstico Lean a executar',
      'Oportunidade de venda de projeto Lean identificada',
      'Resultado documentado dos últimos projetos entregues',
    ],
    telegram_title: '🏭 CONSULTORIA LEAN',
    output_file: 'lean_consulting_report.md',
  },
  {
    key: 'consulting-company-builder',
    folder: 'consulting-company-builder-agent',
    entry: 'consulting_company_builder_agent.js',
    squad: 'operations',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Score de maturidade da consultoria SmartOps (0-100)',
      'Status de evolução dos serviços e pacotes',
      'Processo interno que precisa de padronização urgente',
      'Oportunidade de escalar modelo de consultoria',
      'Próxima metodologia a documentar',
    ],
    telegram_title: '🏢 EMPRESA DE CONSULTORIA',
    output_file: 'consulting_builder_report.md',
  },
  {
    key: 'ai-lab',
    folder: 'ai-lab-agent',
    entry: 'ai_lab_agent.js',
    squad: 'ai-lab',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Novas ferramentas de IA avaliadas esta semana',
      'LLM ou recurso Claude que pode melhorar os agentes',
      'POC (prova de conceito) em andamento: status e resultado',
      'Oportunidade de IA de maior ROI para SmartOps',
      'Experimento de IA recomendado para a próxima semana',
    ],
    telegram_title: '🔬 AI LAB',
    output_file: 'ai_lab_report.md',
  },
  {
    key: 'pricing',
    folder: 'pricing-agent',
    entry: 'pricing_agent.js',
    squad: 'sales',
    priority: 'weekly',
    daily_mode: 'report',
    daily_tasks: [
      'Margem de cada serviço SmartOps vs meta',
      'Comparativo de preços vs concorrência',
      'Oportunidade de ajuste de preço de maior impacto',
      'Análise de elasticidade: impacto de desconto na margem',
      'Precificação do próximo lançamento ou pacote',
    ],
    telegram_title: '💲 PRECIFICAÇÃO',
    output_file: 'pricing_report.md',
  },
  {
    key: 'ai-operations-manager',
    folder: 'ai-operations-manager',
    entry: 'ai_operations_manager.js',
    squad: 'orchestration',
    priority: 'weekly',
    daily_mode: 'status',
    daily_tasks: [
      'Status geral do sistema de IA (todos os agentes)',
      'Agentes com falha ou resultado abaixo do esperado',
      'Score de maturidade do sistema de IA (0-100)',
      'Melhoria de agente recomendada para esta semana',
      'Próxima integração entre agentes a implementar',
    ],
    telegram_title: '🎛️ AI OPERATIONS MANAGER',
    output_file: 'ai_ops_report.md',
  },
];

// Helpers
const DAILY_AGENTS   = AGENTS.filter(a => a.priority === 'daily').sort((a, b) => (a.runs_last ? 1 : 0) - (b.runs_last ? 1 : 0));
const WEEKLY_AGENTS  = AGENTS.filter(a => a.priority === 'weekly');
const ALL_AGENTS     = AGENTS;

const SQUADS = [...new Set(AGENTS.map(a => a.squad))];

function getBySquad(squad) { return AGENTS.filter(a => a.squad === squad); }
function getByKey(key)     { return AGENTS.find(a => a.key === key); }
function getByPriority(p)  { return AGENTS.filter(a => a.priority === p); }

module.exports = { AGENTS, DAILY_AGENTS, WEEKLY_AGENTS, ALL_AGENTS, SQUADS, getBySquad, getByKey, getByPriority };
