#!/usr/bin/env node
/**
 * generate_agent_configs.js — SmartOps IA
 * Gera agent_config.json para todos os agentes seguindo a Arquitetura Universal v2.0
 *
 * Usage:
 *   node scripts/generate_agent_configs.js
 *   node scripts/generate_agent_configs.js --agent ceo-advisor-agent
 *   node scripts/generate_agent_configs.js --squad marketing
 *   node scripts/generate_agent_configs.js --dry-run
 */

const fs   = require('fs');
const path = require('path');

const AGENTS_DIR = path.join(__dirname, '..', 'agents');
const DRY_RUN    = process.argv.includes('--dry-run');
const FILTER_AGENT = (() => { const i = process.argv.indexOf('--agent'); return i !== -1 ? process.argv[i+1] : null; })();
const FILTER_SQUAD = (() => { const i = process.argv.indexOf('--squad'); return i !== -1 ? process.argv[i+1] : null; })();

// ─── CATÁLOGO COMPLETO DE AGENTES ─────────────────────────────────────────────
const AGENT_CATALOG = [
  // ORCHESTRATION
  {
    folder: 'orchestrator-agent',
    name: 'Orchestrator Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'orchestration',
    main_objective: 'Coordenar o pipeline completo de conteúdo: pesquisa → copy + design + vídeo → distribuição',
    modes: ['pipeline', 'brief', 'agenda', 'weekly', 'status', 'report'],
    core_capabilities: ['Coordenação de pipeline', 'BullMQ job queue', 'Tracking de estado', 'Relatórios de orquestração'],
    integrates_with: ['marketing-research-agent', 'copywriter-agent', 'design-agent', 'video-ad-specialist-agent', 'distribution-agent'],
    triggers_agents: ['marketing-research-agent', 'copywriter-agent', 'design-agent', 'video-ad-specialist-agent', 'distribution-agent'],
    output_location: 'outputs/<task_name>_<date>/',
  },
  {
    folder: 'ai-operations-manager',
    name: 'AI Operations Manager',
    version: '2.0.0',
    category: 'Executive',
    squad: 'orchestration',
    main_objective: 'Maestro Central — rotear pedidos para agentes corretos, consolidar respostas e entregar plano integrado',
    modes: ['route', 'diagnose', 'plan', 'project', 'weekly', 'agents', 'status'],
    core_capabilities: ['Roteamento inteligente', 'Diagnóstico universal', 'Plano 5W2H', 'Plano de projeto', 'Consolidação de respostas'],
    integrates_with: ['ceo-advisor-agent', 'chief-of-staff-agent', 'orchestrator-agent'],
    triggers_agents: ['all'],
    output_location: 'agents/ai-operations-manager/outputs/manager_<date>/',
  },

  // SQUAD MARKETING
  {
    folder: 'marketing-research-agent',
    name: 'Marketing Research Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Pesquisar mercado, tendências, concorrentes e oportunidades com Tavily AI',
    modes: ['research', 'trends', 'competitor', 'audience', 'report'],
    core_capabilities: ['Pesquisa com Tavily AI', 'Análise de concorrentes', 'Identificação de tendências', 'Briefing de mercado'],
    integrates_with: ['copywriter-agent', 'seo-agent', 'ads-agent', 'ceo-advisor-agent'],
    triggers_agents: [],
    output_location: 'outputs/<task_name>_<date>/research/',
  },
  {
    folder: 'copywriter-agent',
    name: 'Copywriter Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Criar copy persuasivo para Instagram, Threads, YouTube, e-mail e anúncios',
    modes: ['instagram', 'threads', 'youtube', 'email', 'ad', 'reels', 'carousel'],
    core_capabilities: ['Copy Instagram', 'Copy Threads', 'Metadata YouTube', 'Scripts de reels', 'E-mail marketing', 'Hooks virais'],
    integrates_with: ['marketing-research-agent', 'design-agent'],
    triggers_agents: ['design-agent'],
    output_location: 'outputs/<task_name>_<date>/copy/',
  },
  {
    folder: 'design-agent',
    name: 'Design Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Criar visuais premium com HTML/CSS + Playwright: posts, carrosséis, banners, anúncios',
    modes: ['post', 'carousel', 'banner', 'ad', 'thumbnail'],
    core_capabilities: ['HTML/CSS premium', 'Playwright rendering', 'Design de anúncios', 'Identidade visual SmartOps'],
    integrates_with: ['copywriter-agent', 'distribution-agent'],
    triggers_agents: ['distribution-agent'],
    output_location: 'outputs/<task_name>_<date>/ads/',
  },
  {
    folder: 'distribution-agent',
    name: 'Distribution Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Publicar conteúdo em múltiplos canais e gerenciar calendário editorial',
    modes: ['publish', 'schedule', 'calendar', 'status'],
    core_capabilities: ['Publicação Instagram', 'Publicação YouTube', 'Calendário editorial', 'Scheduling'],
    integrates_with: ['copywriter-agent', 'design-agent', 'video-ad-specialist-agent'],
    triggers_agents: [],
    output_location: 'outputs/<task_name>_<date>/distribution/',
  },
  {
    folder: 'seo-agent',
    name: 'SEO Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Estratégia de SEO orgânico: pesquisa de palavras-chave, clusters e autoridade',
    modes: ['keywords', 'cluster', 'audit', 'opportunity', 'report'],
    core_capabilities: ['Pesquisa de palavras-chave', 'Clusters de conteúdo', 'Auditoria SEO', 'Link building', 'Autoridade tópica'],
    integrates_with: ['marketing-research-agent', 'copywriter-agent'],
    triggers_agents: [],
    output_location: 'agents/seo-agent/outputs/seo_<date>/',
  },
  {
    folder: 'video-ad-specialist-agent',
    name: 'Video Ad Specialist Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Criar criativos de vídeo, VSL, UGC e roteiros para reels e anúncios',
    modes: ['vsl', 'reels', 'ugc', 'script', 'storyboard'],
    core_capabilities: ['Roteiros de vídeo', 'VSL', 'Storyboard', 'Scripts de reels', 'UGC strategy'],
    integrates_with: ['marketing-research-agent', 'copywriter-agent'],
    triggers_agents: [],
    output_location: 'outputs/<task_name>_<date>/video/',
  },
  {
    folder: 'content-performance-agent',
    name: 'Content Performance Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Analisar performance de conteúdo: alcance, engajamento, conversão e ROI',
    modes: ['analyze', 'report', 'optimize'],
    core_capabilities: ['Análise de engajamento', 'ROI de conteúdo', 'Otimização de publicações', 'Relatórios'],
    integrates_with: ['website-analytics-agent', 'cro-agent'],
    triggers_agents: [],
    output_location: 'agents/content-performance-agent/outputs/',
  },

  // SQUAD GROWTH
  {
    folder: 'cro-agent',
    name: 'CRO Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Otimizar conversão em landing pages, funis e jornada do cliente',
    modes: ['audit', 'funnel', 'landing-page', 'ab-test', 'report'],
    core_capabilities: ['Auditoria de conversão', 'Otimização de funil', 'A/B testing', 'CRO de landing page', 'Heatmap analysis'],
    integrates_with: ['website-analytics-agent', 'ads-agent', 'customer-journey-agent'],
    triggers_agents: [],
    output_location: 'agents/cro-agent/outputs/cro_<date>/',
  },
  {
    folder: 'revenue-agent',
    name: 'Revenue Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Análise de receita, ROI, CAC, LTV e atribuição de canais',
    modes: ['analyze', 'cac', 'ltv', 'attribution', 'forecast', 'report'],
    core_capabilities: ['Análise de receita', 'CAC e LTV', 'Atribuição multicanal', 'Forecasting de receita', 'ROI por canal'],
    integrates_with: ['financial-intelligence-agent', 'ads-agent', 'ceo-advisor-agent'],
    triggers_agents: [],
    output_location: 'agents/revenue-agent/outputs/revenue_<date>/',
  },
  {
    folder: 'ads-agent',
    name: 'Ads Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Gestão e otimização de Google Ads e Meta Ads',
    modes: ['google', 'meta', 'report', 'optimize', 'ceo-brief'],
    core_capabilities: ['Google Ads', 'Meta Ads', 'ROAS e CPA', 'Análise criativa', 'Budget reallocation'],
    integrates_with: ['marketing-research-agent', 'cro-agent', 'revenue-agent'],
    triggers_agents: [],
    output_location: 'agents/ads-agent/outputs/ads_<date>/',
  },
  {
    folder: 'customer-journey-agent',
    name: 'Customer Journey Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Mapear e otimizar a jornada completa do cliente, do awareness ao advocacy',
    modes: ['map', 'analyze', 'optimize', 'touchpoints', 'report'],
    core_capabilities: ['Mapeamento de jornada', 'Identificação de fricções', 'Otimização de touchpoints', 'Jornada B2B'],
    integrates_with: ['cro-agent', 'client-success-agent', 'sales-intelligence-agent'],
    triggers_agents: [],
    output_location: 'agents/customer-journey-agent/outputs/',
  },
  {
    folder: 'lead-scoring-agent',
    name: 'Lead Scoring Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Qualificar e priorizar leads por probabilidade de fechamento e valor potencial',
    modes: ['score', 'rank', 'analyze', 'report'],
    core_capabilities: ['Scoring de leads', 'Qualificação BANT', 'Priorização de pipeline', 'Lead intelligence'],
    integrates_with: ['sales-intelligence-agent', 'crm'],
    triggers_agents: ['sales-intelligence-agent'],
    output_location: 'agents/lead-scoring-agent/outputs/',
  },
  {
    folder: 'website-analytics-agent',
    name: 'Website Analytics Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Analisar comportamento no site via GA4: sessões, eventos, conversões',
    modes: ['analyze', 'sessions', 'events', 'conversions', 'report'],
    core_capabilities: ['GA4', 'Análise de sessões', 'Análise de eventos', 'Funil de conversão', 'Relatórios de site'],
    integrates_with: ['cro-agent', 'seo-agent', 'ads-agent'],
    triggers_agents: [],
    output_location: 'agents/website-analytics-agent/outputs/',
  },
  {
    folder: 'growth-intelligence-agent',
    name: 'Growth Intelligence Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Identificar alavancas de crescimento e oportunidades de escala',
    modes: ['analyze', 'levers', 'opportunities', 'report'],
    core_capabilities: ['Análise de crescimento', 'Identificação de alavancas', 'Growth hacking', 'Escala de canais'],
    integrates_with: ['revenue-agent', 'cro-agent', 'ceo-advisor-agent'],
    triggers_agents: [],
    output_location: 'agents/growth-intelligence-agent/outputs/',
  },
  {
    folder: 'revenue-intelligence-agent',
    name: 'Revenue Intelligence Agent',
    version: '2.0.0',
    category: 'Growth',
    squad: 'growth',
    main_objective: 'Análise preditiva de receita, forecasting e identificação de padrões',
    modes: ['forecast', 'patterns', 'analyze', 'report'],
    core_capabilities: ['Forecasting', 'Análise preditiva', 'Padrões de receita', 'Churn prediction'],
    integrates_with: ['financial-intelligence-agent', 'revenue-agent'],
    triggers_agents: [],
    output_location: 'agents/revenue-intelligence-agent/outputs/',
  },

  // SQUAD OPERATIONS
  {
    folder: 'lean-agent',
    name: 'Lean Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Identificar os 8 desperdícios e mapear fluxo de valor com metodologia Lean',
    modes: ['analyze', 'vsm', 'waste', 'kaizen', 'report'],
    core_capabilities: ['8 desperdícios', 'VSM', 'Lean Manufacturing', 'Just-in-time', '5S', 'Poka-yoke'],
    integrates_with: ['kaizen-agent', 'six-sigma-agent', 'automation-agent'],
    triggers_agents: ['kaizen-agent'],
    output_location: 'agents/lean-agent/outputs/lean_<date>/',
  },
  {
    folder: 'six-sigma-agent',
    name: 'Six Sigma Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Reduzir defeitos e variabilidade com DMAIC e ferramentas Six Sigma',
    modes: ['dmaic', 'define', 'measure', 'analyze', 'improve', 'control', 'report'],
    core_capabilities: ['DMAIC', 'FMEA', 'Análise de Causa Raiz', 'Controle Estatístico', 'Diagrama de Ishikawa'],
    integrates_with: ['lean-agent', 'process-mining-agent'],
    triggers_agents: [],
    output_location: 'agents/six-sigma-agent/outputs/',
  },
  {
    folder: 'kaizen-agent',
    name: 'Kaizen Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Implementar melhoria contínua diária com ciclos Kaizen e PDCA',
    modes: ['pdca', 'event', 'daily', 'report'],
    core_capabilities: ['Ciclo PDCA', 'Eventos Kaizen', 'Melhoria diária', 'Gestão visual', 'Gemba Walk'],
    integrates_with: ['lean-agent', 'knowledge-management-agent'],
    triggers_agents: [],
    output_location: 'agents/kaizen-agent/outputs/',
  },
  {
    folder: 'process-mining-agent',
    name: 'Process Mining Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Descobrir processos reais a partir de dados de sistemas e logs',
    modes: ['discover', 'analyze', 'compare', 'report'],
    core_capabilities: ['Process discovery', 'Conformance checking', 'Performance analysis', 'Análise de logs'],
    integrates_with: ['lean-agent', 'automation-agent'],
    triggers_agents: ['automation-agent'],
    output_location: 'agents/process-mining-agent/outputs/',
  },
  {
    folder: 'automation-agent',
    name: 'Automation Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Desenhar e implementar automações com n8n, APIs e RPA',
    modes: ['design', 'map', 'build', 'test', 'monitor', 'report'],
    core_capabilities: ['n8n workflows', 'Mapeamento de automação', 'API integration', 'RPA', 'Webhook design'],
    integrates_with: ['lean-agent', 'ai-automation-agent'],
    triggers_agents: [],
    output_location: 'agents/automation-agent/outputs/',
  },
  {
    folder: 'ai-automation-agent',
    name: 'AI Automation Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Automatizar processos com IA: LangGraph, CrewAI, Claude API, n8n + IA',
    modes: ['design', 'build', 'deploy', 'monitor'],
    core_capabilities: ['LangGraph', 'CrewAI', 'Claude API', 'n8n + IA', 'Agentes autônomos'],
    integrates_with: ['automation-agent', 'ai-lab-agent'],
    triggers_agents: [],
    output_location: 'agents/ai-automation-agent/outputs/',
  },
  {
    folder: 'lean-consulting-agent',
    name: 'Lean Consulting Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Estruturar e executar projetos de consultoria Lean para clientes SME',
    modes: ['diagnose', 'project', 'proposal', 'report', 'case-study'],
    core_capabilities: ['Diagnóstico Lean', 'Projeto Lean completo', 'Treinamento', 'Acompanhamento de resultados'],
    integrates_with: ['lean-agent', 'six-sigma-agent', 'proposal-agent'],
    triggers_agents: ['lean-agent', 'proposal-agent'],
    output_location: 'agents/lean-consulting-agent/outputs/',
  },
  {
    folder: 'knowledge-management-agent',
    name: 'Knowledge Management Agent',
    version: '2.0.0',
    category: 'Knowledge',
    squad: 'knowledge',
    main_objective: 'Criar e manter SOPs, playbooks e base de conhecimento da empresa',
    modes: ['create-sop', 'update', 'search', 'organize', 'report'],
    core_capabilities: ['SOPs', 'Playbooks', 'Base de conhecimento', 'Onboarding docs', 'Gestão de aprendizados'],
    integrates_with: ['kaizen-agent', 'organizational-learning-agent'],
    triggers_agents: [],
    output_location: 'agents/knowledge-management-agent/outputs/',
  },
  {
    folder: 'experimentation-agent',
    name: 'Experimentation Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Estruturar experimentos, testes A/B e validação de hipóteses',
    modes: ['design', 'run', 'analyze', 'report'],
    core_capabilities: ['Design de experimentos', 'Teste A/B', 'Hipóteses', 'MVP validation', 'Análise estatística'],
    integrates_with: ['cro-agent', 'marketing-research-agent'],
    triggers_agents: [],
    output_location: 'agents/experimentation-agent/outputs/',
  },
  {
    folder: 'organizational-learning-agent',
    name: 'Organizational Learning Agent',
    version: '2.0.0',
    category: 'Knowledge',
    squad: 'knowledge',
    main_objective: 'Capturar aprendizados, melhorar processos e fortalecer cultura organizacional',
    modes: ['retrospective', 'lessons', 'culture', 'report'],
    core_capabilities: ['Retrospectivas', 'Lições aprendidas', 'Gestão de conhecimento', 'Cultura de aprendizado'],
    integrates_with: ['knowledge-management-agent', 'kaizen-agent'],
    triggers_agents: [],
    output_location: 'agents/organizational-learning-agent/outputs/',
  },

  // SQUAD SALES
  {
    folder: 'sales-intelligence-agent',
    name: 'Sales Intelligence Agent',
    version: '2.0.0',
    category: 'Sales',
    squad: 'sales',
    main_objective: 'Qualificar leads, superar objeções e criar estratégia comercial de alto desempenho',
    modes: ['qualify', 'script', 'objections', 'pipeline', 'crm', 'report'],
    core_capabilities: ['Scripts de vendas', 'Qualificação BANT', 'Superação de objeções', 'Pipeline management', 'CRM'],
    integrates_with: ['lead-scoring-agent', 'proposal-agent', 'offer-optimization-agent'],
    triggers_agents: ['proposal-agent'],
    output_location: 'agents/sales-intelligence-agent/outputs/sales_<date>/',
  },
  {
    folder: 'proposal-agent',
    name: 'Proposal Agent',
    version: '2.0.0',
    category: 'Sales',
    squad: 'sales',
    main_objective: 'Criar propostas comerciais personalizadas de alto valor percebido',
    modes: ['create', 'template', 'customize', 'review'],
    core_capabilities: ['Proposta comercial', 'Diagnóstico do cliente', 'ROI da proposta', 'Escopo de projeto'],
    integrates_with: ['sales-intelligence-agent', 'pricing-agent', 'offer-optimization-agent'],
    triggers_agents: [],
    output_location: 'agents/proposal-agent/outputs/',
  },
  {
    folder: 'offer-optimization-agent',
    name: 'Offer Optimization Agent',
    version: '2.0.0',
    category: 'Sales',
    squad: 'sales',
    main_objective: 'Otimizar ofertas, pacotes e proposta de valor para maximizar conversão e ticket',
    modes: ['analyze', 'optimize', 'package', 'test'],
    core_capabilities: ['Análise de oferta', 'Pacotes de serviços', 'Value proposition', 'Precificação por valor'],
    integrates_with: ['pricing-agent', 'proposal-agent', 'cro-agent'],
    triggers_agents: [],
    output_location: 'agents/offer-optimization-agent/outputs/',
  },
  {
    folder: 'pricing-agent',
    name: 'Pricing Agent',
    version: '2.0.0',
    category: 'Sales',
    squad: 'sales',
    main_objective: 'Definir precificação estratégica baseada em valor percebido, margem e mercado',
    modes: ['analyze', 'model', 'strategy', 'report'],
    core_capabilities: ['Precificação por valor', 'Análise de margem', 'Modelos de pricing', 'Elasticidade de preço'],
    integrates_with: ['offer-optimization-agent', 'financial-intelligence-agent'],
    triggers_agents: [],
    output_location: 'agents/pricing-agent/outputs/',
  },

  // SQUAD EXECUTIVE
  {
    folder: 'ceo-advisor-agent',
    name: 'CEO Advisor Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Consolidar insights de todos os agentes e gerar decisões executivas priorizadas por ROI',
    modes: ['brief', 'daily-plan', 'priority', 'decision', 'weekly-review', 'alert'],
    core_capabilities: ['Decisão executiva', 'Priorização ROI', 'Plano do dia', 'Revisão semanal', 'Alertas críticos'],
    integrates_with: ['chief-of-staff-agent', 'financial-intelligence-agent', 'executive-dashboard-agent'],
    triggers_agents: ['chief-of-staff-agent'],
    output_location: 'agents/ceo-advisor-agent/outputs/ceo_<date>/',
  },
  {
    folder: 'chief-of-staff-agent',
    name: 'Chief of Staff Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Transformar estratégia em execução: criar planos táticos e acompanhar entregas',
    modes: ['plan', 'weekly', 'track', 'delegate', 'report'],
    core_capabilities: ['Plano de execução', 'Delegação de tarefas', 'Acompanhamento', 'Comunicação executiva'],
    integrates_with: ['ceo-advisor-agent', 'knowledge-management-agent'],
    triggers_agents: [],
    output_location: 'agents/chief-of-staff-agent/outputs/',
  },
  {
    folder: 'executive-dashboard-agent',
    name: 'Executive Dashboard Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Consolidar KPIs de todos os squads em dashboards executivos diários/semanais/mensais',
    modes: ['daily', 'weekly', 'monthly', 'alert', 'report'],
    core_capabilities: ['Dashboard executivo', 'KPI consolidado', 'Alertas automáticos', 'Relatório multi-squad'],
    integrates_with: ['ceo-advisor-agent', 'financial-intelligence-agent'],
    triggers_agents: ['ceo-advisor-agent'],
    output_location: 'agents/executive-dashboard-agent/outputs/',
  },
  {
    folder: 'competitor-intelligence-agent',
    name: 'Competitor Intelligence Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Monitorar concorrentes e identificar oportunidades de diferenciação',
    modes: ['monitor', 'analyze', 'benchmark', 'report'],
    core_capabilities: ['Monitoramento de concorrentes', 'Análise competitiva', 'Benchmarking', 'Oportunidades de diferenciação'],
    integrates_with: ['marketing-research-agent', 'strategic-planning-agent'],
    triggers_agents: [],
    output_location: 'agents/competitor-intelligence-agent/outputs/',
  },
  {
    folder: 'strategic-planning-agent',
    name: 'Strategic Planning Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Criar planos estratégicos 30/90/180 dias, definir OKRs e prioridades',
    modes: ['30-days', '90-days', '180-days', 'okr', 'review', 'report'],
    core_capabilities: ['OKRs', 'Plano 90 dias', 'Plano 180 dias', 'Revisão estratégica', 'Priorização'],
    integrates_with: ['ceo-advisor-agent', 'executive-dashboard-agent', 'chief-of-staff-agent'],
    triggers_agents: ['chief-of-staff-agent'],
    output_location: 'agents/strategic-planning-agent/outputs/',
  },
  {
    folder: 'market-opportunity-agent',
    name: 'Market Opportunity Agent',
    version: '2.0.0',
    category: 'Executive',
    squad: 'executive',
    main_objective: 'Identificar e priorizar oportunidades de mercado e novos nichos por ROI',
    modes: ['scan', 'analyze', 'prioritize', 'report'],
    core_capabilities: ['Identificação de oportunidades', 'Análise de nicho', 'TAM/SAM/SOM', 'Priorização por ROI'],
    integrates_with: ['marketing-research-agent', 'strategic-planning-agent'],
    triggers_agents: [],
    output_location: 'agents/market-opportunity-agent/outputs/',
  },

  // SQUAD FINANCE
  {
    folder: 'financial-intelligence-agent',
    name: 'Financial Intelligence Agent',
    version: '2.0.0',
    category: 'Finance',
    squad: 'finance',
    main_objective: 'Analisar saúde financeira: receita, margem, ROI, fluxo de caixa e custos',
    modes: ['weekly', 'monthly', 'cashflow', 'margin', 'roi', 'report'],
    core_capabilities: ['DRE simplificado', 'Fluxo de caixa', 'Margem de contribuição', 'ROI por projeto', 'Alertas financeiros'],
    integrates_with: ['ceo-advisor-agent', 'revenue-agent', 'pricing-agent'],
    triggers_agents: ['ceo-advisor-agent'],
    output_location: 'outputs/finance_<date>/finance/',
  },

  // SQUAD CLIENT SUCCESS
  {
    folder: 'client-success-agent',
    name: 'Client Success Agent',
    version: '2.0.0',
    category: 'Client',
    squad: 'client',
    main_objective: 'Monitorar saúde dos clientes, reduzir churn e aumentar expansão',
    modes: ['health-check', 'onboarding', 'retention', 'expansion', 'report'],
    core_capabilities: ['Health score', 'Onboarding', 'Churn prevention', 'Upsell/cross-sell', 'NPS'],
    integrates_with: ['risk-agent', 'proposal-agent'],
    triggers_agents: ['risk-agent'],
    output_location: 'agents/client-success-agent/outputs/',
  },
  {
    folder: 'risk-agent',
    name: 'Risk Agent',
    version: '2.0.0',
    category: 'Client',
    squad: 'client',
    main_objective: 'Identificar riscos operacionais, financeiros e de clientes com ações preventivas',
    modes: ['scan', 'analyze', 'alert', 'mitigate', 'report'],
    core_capabilities: ['Análise de risco', 'Alertas preventivos', 'Plano de contingência', 'Risk matrix'],
    integrates_with: ['client-success-agent', 'financial-intelligence-agent', 'ceo-advisor-agent'],
    triggers_agents: ['ceo-advisor-agent'],
    output_location: 'agents/risk-agent/outputs/',
  },

  // SQUAD KNOWLEDGE
  {
    folder: 'case-study-agent',
    name: 'Case Study Agent',
    version: '2.0.0',
    category: 'Knowledge',
    squad: 'knowledge',
    main_objective: 'Criar estudos de caso com resultados mensuráveis, ROI documentado e prova social',
    modes: ['create', 'template', 'publish'],
    core_capabilities: ['Estudo de caso', 'ROI documentado', 'Antes/Depois', 'Prova social', 'Content marketing'],
    integrates_with: ['client-success-agent', 'copywriter-agent'],
    triggers_agents: ['copywriter-agent'],
    output_location: 'agents/case-study-agent/outputs/',
  },
  {
    folder: 'productization-agent',
    name: 'Productization Agent',
    version: '2.0.0',
    category: 'Knowledge',
    squad: 'knowledge',
    main_objective: 'Transformar consultoria em produtos escaláveis e serviços recorrentes',
    modes: ['design', 'package', 'price', 'launch'],
    core_capabilities: ['Produtização', 'Serviços recorrentes', 'Digitalização de oferta', 'Escalabilidade'],
    integrates_with: ['offer-optimization-agent', 'pricing-agent', 'strategic-planning-agent'],
    triggers_agents: [],
    output_location: 'agents/productization-agent/outputs/',
  },

  // SQUAD PERSONAL BRAND
  {
    folder: 'personal-brand-agent',
    name: 'Personal Brand Agent',
    version: '2.0.0',
    category: 'Brand',
    squad: 'brand',
    main_objective: 'Desenvolver narrativa, posicionamento e estratégia de marca pessoal',
    modes: ['audit', 'strategy', 'content', 'positioning', 'report'],
    core_capabilities: ['Narrativa pessoal', 'Posicionamento', 'Estratégia de conteúdo pessoal', 'Identidade de marca'],
    integrates_with: ['authority-building-agent', 'copywriter-agent'],
    triggers_agents: [],
    output_location: 'agents/personal-brand-agent/outputs/',
  },
  {
    folder: 'authority-building-agent',
    name: 'Authority Building Agent',
    version: '2.0.0',
    category: 'Brand',
    squad: 'brand',
    main_objective: 'Construir autoridade via palestras, artigos, lives, podcasts e especialização',
    modes: ['plan', 'create', 'promote', 'measure'],
    core_capabilities: ['Palestras', 'Artigos de autoridade', 'Podcasts', 'Lives', 'Publicações'],
    integrates_with: ['personal-brand-agent', 'copywriter-agent', 'seo-agent'],
    triggers_agents: [],
    output_location: 'agents/authority-building-agent/outputs/',
  },
  {
    folder: 'partnership-agent',
    name: 'Partnership Agent',
    version: '2.0.0',
    category: 'Brand',
    squad: 'brand',
    main_objective: 'Identificar e estruturar parcerias estratégicas B2B e co-marketing',
    modes: ['identify', 'outreach', 'structure', 'report'],
    core_capabilities: ['Mapeamento de parceiros', 'Co-marketing', 'Acordos B2B', 'Joint ventures'],
    integrates_with: ['personal-brand-agent', 'sales-intelligence-agent'],
    triggers_agents: [],
    output_location: 'agents/partner-ship-agent/outputs/',
  },
  {
    folder: 'relationship-coach-agent',
    name: 'Relationship Coach Agent',
    version: '2.0.0',
    category: 'Brand',
    squad: 'brand',
    main_objective: 'Orientar estratégia de relacionamento, networking e abordagem de prospects',
    modes: ['coach', 'script', 'followup', 'networking'],
    core_capabilities: ['Scripts de abordagem', 'Follow-up strategy', 'Networking', 'Mensagens de prospecção'],
    integrates_with: ['sales-intelligence-agent', 'personal-brand-agent'],
    triggers_agents: [],
    output_location: 'agents/relationship-coach-agent/outputs/',
  },

  // SQUAD AI LAB
  {
    folder: 'ai-lab-agent',
    name: 'AI Lab Agent',
    version: '2.0.0',
    category: 'AI Lab',
    squad: 'ai-lab',
    main_objective: 'Avaliar e experimentar novas tecnologias de IA para aplicação no negócio',
    modes: ['research', 'test', 'evaluate', 'report'],
    core_capabilities: ['Avaliação de LLMs', 'Experimentos com IA', 'Benchmarking de ferramentas', 'Relatório de inovação'],
    integrates_with: ['ai-automation-agent', 'ceo-advisor-agent'],
    triggers_agents: [],
    output_location: 'agents/ai-lab-agent/outputs/',
  },

  // OUTROS
  {
    folder: 'consulting-company-builder-agent',
    name: 'Consulting Company Builder Agent',
    version: '2.0.0',
    category: 'Operations',
    squad: 'operations',
    main_objective: 'Estruturar e escalar empresa de consultoria: metodologia, serviços, operação e crescimento',
    modes: ['structure', 'services', 'methodology', 'operations', 'growth', 'report'],
    core_capabilities: ['Estrutura de consultoria', 'Modelagem de serviços', 'Operacionalização', 'Escala de consultoria'],
    integrates_with: ['productization-agent', 'pricing-agent', 'lean-consulting-agent'],
    triggers_agents: [],
    output_location: 'agents/consulting-company-builder-agent/outputs/',
  },
  {
    folder: 'ad-creative-designer-agent',
    name: 'Ad Creative Designer Agent',
    version: '2.0.0',
    category: 'Marketing',
    squad: 'marketing',
    main_objective: 'Criar anúncios visuais otimizados para performance em Google e Meta Ads',
    modes: ['create', 'optimize', 'ab-test', 'report'],
    core_capabilities: ['Ad creatives', 'HTML/CSS ads', 'A/B testing de criativos', 'Design para conversão'],
    integrates_with: ['ads-agent', 'copywriter-agent'],
    triggers_agents: [],
    output_location: 'outputs/<task_name>_<date>/ads/',
  },
];

// ─── TEMPLATE DE agent_config.json ───────────────────────────────────────────
function buildConfig(agent) {
  return {
    agent_name:      agent.name,
    version:         agent.version || '2.0.0',
    category:        agent.category,
    squad:           agent.squad,
    main_objective:  agent.main_objective,
    primary_users:   ['owner', 'manager'],
    modes:           agent.modes || ['analyze', 'report'],
    core_capabilities: agent.core_capabilities || [
      'Diagnóstico',
      'Plano de ação',
      'Relatórios',
      'Templates',
      'Análise de dados',
      'Priorização',
    ],
    forbidden_behaviors: [
      'Inventar dados',
      'Prometer resultado garantido',
      'Responder de forma genérica',
      'Ignorar riscos',
      'Deixar o usuário sem próximo passo',
    ],
    default_output_format: [
      'Resumo executivo',
      'Diagnóstico',
      'Recomendação principal',
      'Plano de ação priorizado (P1/P2/P3)',
      'Indicadores de sucesso',
      'Próximos 3 passos',
    ],
    priority_system: {
      P1: 'Urgente — afeta receita, cliente, segurança',
      P2: 'Alta — impacto relevante em curto prazo',
      P3: 'Média — melhoria importante, não emergencial',
      P4: 'Baixa — otimização complementar',
    },
    confidence_levels:  ['Alta', 'Média', 'Baixa', 'Insuficiente'],
    integrates_with:    agent.integrates_with || [],
    triggers_agents:    agent.triggers_agents || [],
    output_location:    agent.output_location || `agents/${agent.folder}/outputs/`,
    quality_checklist: [
      'A resposta resolve o pedido?',
      'Está específica (não genérica)?',
      'Tem próximo passo claro?',
      'Tem prioridade definida?',
      'Tem entregável concreto?',
      'Menciona riscos?',
    ],
    architecture: 'universal-v2',
    last_updated: new Date().toISOString().split('T')[0],
  };
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────
let filtered = AGENT_CATALOG;
if (FILTER_AGENT) filtered = filtered.filter(a => a.folder === FILTER_AGENT);
if (FILTER_SQUAD) filtered = filtered.filter(a => a.squad === FILTER_SQUAD);

console.log(`\n🔧 SmartOps IA — Gerador de agent_config.json`);
console.log(`   Arquitetura Universal v2.0`);
console.log(`   Agentes a processar: ${filtered.length}/${AGENT_CATALOG.length}`);
if (DRY_RUN) console.log('   Modo: DRY RUN (não salva arquivos)\n');

let created = 0, skipped = 0, updated = 0;

for (const agent of filtered) {
  const agentDir = path.join(AGENTS_DIR, agent.folder);
  const configPath = path.join(agentDir, 'agent_config.json');

  if (!fs.existsSync(agentDir)) {
    console.log(`  ⚠️  Pasta não encontrada: agents/${agent.folder}`);
    skipped++;
    continue;
  }

  const config = buildConfig(agent);
  const content = JSON.stringify(config, null, 2);

  if (DRY_RUN) {
    console.log(`  ✓ [DRY] ${agent.folder}/agent_config.json`);
    created++;
    continue;
  }

  const exists = fs.existsSync(configPath);
  fs.writeFileSync(configPath, content, 'utf-8');
  console.log(`  ${exists ? '↺' : '+'} ${agent.folder}/agent_config.json`);
  if (exists) updated++; else created++;
}

console.log(`\n✅ Concluído: ${created} criados | ${updated} atualizados | ${skipped} pulados`);
console.log(`   Referência: knowledge/UNIVERSAL_ARCHITECTURE.md\n`);
